typeidea/typeidea/urls.py
import xadmin

from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter

from blog.apis import PostViewSet, CategoryViewSet
from blog.views import IndexView, CategoryView, TagView, PostDetailView, SearchView, AuthorView
from config.views import LinkListView
from comment.views import CommentView

from blog.rss import LatestPostFeed
from blog.sitemap import PostSiteMap

from .custom_site import custom_site
from .autocomplete import CategoryAutocompleteView, TagAutocompleteView

router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')
router.register(r'category', CategoryViewSet, basename='api-category')

urlpatterns = [
                  path('super_admin/', admin.site.urls, name='super-admin'),
                  path('admin/', custom_site.urls, name='admin'),
                  path('xadmin/', xadmin.site.urls, name='xadmin'),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('api/', include(router.urls)),
                  path('api/docs/', include_docs_urls(title='typeidea apis')),

                  re_path(r'^$', cache_page(60 * 20, key_prefix='sitemap_cache_')(IndexView.as_view()), name='index'),
                  re_path(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
                  re_path(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
                  re_path(r'^post/(?P<post_id>\d+)/$', PostDetailView.as_view(), name='post-detail'),
                  re_path(r'^links/$', LinkListView.as_view(), name='links'),
                  re_path(r'^comment/$', CommentView.as_view(), name='comment'),
                  re_path(r'^search/$', SearchView.as_view(), name='search'),
                  re_path(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
                  re_path(r'^rss|feed$', LatestPostFeed(), name='rss'),
                  re_path(r'^sitemap\.xml$', cache_page(60 * 20, key_prefix='sitemap_cache_')(sitemap_views.sitemap),
                          {'sitemaps': {'posts': PostSiteMap}}),
                  re_path(r'^category-autocomplete/$', CategoryAutocompleteView.as_view(),
                          name='category-autocomplete'),
                  re_path(r'^tag-autocomplete/$', TagAutocompleteView.as_view(), name='tag-autocomplete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += [
        path('silk/', include('silk.urls', namespace='silk'))
    ]

typeidea/comment/models.py
from django.db import models


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除')
    )

    target = models.CharField(max_length=100, verbose_name='评论目标')
    content = models.CharField(max_length=1024, verbose_name='内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

typeidea/comment/forms.py
import mistune
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': 'width:60%;'}
        )
    )

    email = forms.EmailField(
        label='邮箱',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': 'width:60%;'}
        )
    )

    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': 'width: 60%;'}
        )
    )

    content = forms.CharField(
        label='内容',
        max_length=1024,
        widget=forms.widgets.Textarea(
            attrs={'row': 6, 'cols': 60, 'class': 'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 10:
            raise forms.ValidationError('内容长度必须大于10')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

typeidea/comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from .forms import CommentForm


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }

        return self.render_to_response(context)

typeidea/typeidea/themes/bootstrap/templates/comment/block.html
<hr/>
<div class="comment">
    <form class="form-group" action="{% url 'comment' %}" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <input type="submit" value="提交">
    </form>

    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="comment-nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                <span>{{ comment.created_time }}</span>
            </div>

            <div class="comment-content">
                {% autoescape off %}
                    {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

typeidea/typeidea/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>

    <style>
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }

        .errorlist {
            color: red;
        }

        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
    <div class="result">
        {% if succeed %}
            <h1>评论成功</h1>
            <a href="{{ target }}">返回</a>
        {% else %}
            <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>